"""Generate the small checked-in TypeScript client from the OpenAPI contract."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
SPEC_PATH = ROOT / "packages/contracts/spec/openapi.json"
OUTPUT_PATH = ROOT / "apps/web/lib/generated/api-client.ts"


def ts_type(schema: dict[str, object]) -> str:
    if schema.get("type") == "string":
        return "string"
    if schema.get("type") == "integer" or schema.get("type") == "number":
        return "number"
    if schema.get("type") == "boolean":
        return "boolean"
    return "unknown"


def generate() -> str:
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    lines = [
        "// Generated by scripts/generate_client.py; do not edit manually.",
        "",
    ]
    schemas = spec["components"]["schemas"]
    for name in sorted(schemas):
        schema = schemas[name]
        lines.append(f"export interface {name} {{")
        for property_name in sorted(schema["properties"]):
            property_schema = schema["properties"][property_name]
            optional = "" if property_name in schema["required"] else "?"
            lines.append(f"  {property_name}{optional}: {ts_type(property_schema)};")
        lines.extend(["}", ""])

    for path, methods in sorted(spec["paths"].items()):
        for method, operation in sorted(methods.items()):
            operation_id = operation["operationId"]
            response_schema = operation["responses"]["200"]["content"]["application/json"]["schema"]
            response_name = response_schema["$ref"].split("/")[-1]
            lines.extend(
                [
                    f"export async function {operation_id}("
                    f"baseUrl = \"\"): Promise<{response_name}> {{",
                    f"  const response = await fetch(`${{baseUrl}}{path}`);",
                    "  if (!response.ok) throw new Error("
                    "`API request failed: ${response.status}`);",
                    f"  return response.json() as Promise<{response_name}>;",
                    "}",
                    "",
                ]
            )
    return "\n".join(lines)


def main(check: bool = False) -> int:
    generated = generate()
    if check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != generated:
            print(f"contract drift: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main("--check" in sys.argv))
